version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/deploy
hooks:
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/run_app.sh
      timeout: 300
      runas: root
